<!--
Copyright © 2020, Oracle and/or its affiliates. All rights reserved.
Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
-->
<xsl:stylesheet version="1.0" exclude-result-prefixes=" oracle-xsl-mapper xsl bpelpull ftp" xmlns:ftp="__LIST__WSDL__TYPE__NAMESPACE__" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:bpelpull="http://xmlns.oracle.com/ics/scheduler/pull" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://xmlns.oracle.com/cloud/list/pull">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="BpelPull.xsd"/>
        <oracle-xsl-mapper:rootElement name="BpelPullRequest" namespace="http://xmlns.oracle.com/ics/scheduler/pull"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="__LIST__WSDL__LOCATION__"/>
        <oracle-xsl-mapper:rootElement name="List" namespace="__LIST__WSDL__TYPE__NAMESPACE__"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.2.0.0(XSLT Build 160130.1831.1526) AT [FRI FEB 05 13:13:22 IST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ftp:List>
      <PullRequest>
        <maxItems>
          <xsl:value-of select="/bpelpull:BpelPullRequest/bpelpull:maxItems"/>
        </maxItems>
        <position>
          <xsl:value-of select="/bpelpull:BpelPullRequest/bpelpull:position"/>
        </position>
        <pullContext>
          <xsl:value-of select="/bpelpull:BpelPullRequest/bpelpull:pullContext"/>
        </pullContext>
        <bindParameters>
          <xsl:for-each select="/bpelpull:BpelPullRequest/bpelpull:bindParameters/bpelpull:Parameter">
            <parameter name="{bpelpull:name}">
              <xsl:value-of select="bpelpull:value"/>
            </parameter>
          </xsl:for-each>
        </bindParameters>
      </PullRequest>
    </ftp:List>
  </xsl:template>
</xsl:stylesheet>