<!--
Copyright © 2020, Oracle and/or its affiliates. All rights reserved.
Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
-->
<xsl:stylesheet version="1.0" exclude-result-prefixes=" oracle-xsl-mapper xsl ftp cloudpull" xmlns:ftp="__LIST__WSDL__TYPE__NAMESPACE__" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns="http://xmlns.oracle.com/ics/scheduler/pull" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:cloudpull="http://xmlns.oracle.com/cloud/list/pull">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="__LIST__WSDL__LOCATION__"/>
        <oracle-xsl-mapper:rootElement name="ListResponse" namespace="__LIST__WSDL__TYPE__NAMESPACE__"/>
        <oracle-xsl-mapper:source type="XSD">
          <oracle-xsl-mapper:schema location="BpelContext.xsd"/>
          <oracle-xsl-mapper:rootElement name="BpelContext" namespace="http://xmlns.oracle.com/ics/scheduler/bpelcontext"/>
          <oracle-xsl-mapper:param name="bpelContext"/>
        </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="BpelPull.xsd"/>
        <oracle-xsl-mapper:rootElement name="BpelPullResponse" namespace="http://xmlns.oracle.com/ics/scheduler/pull"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.2.0.0(XSLT Build 160130.1831.1526) AT [FRI FEB 05 13:13:22 IST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="bpelContext"/>
  <xsl:template match="/">
    <BpelPullResponse>
      <ItemCount>
        <xsl:value-of select="/ftp:ListResponse/cloudpull:PullResponse/cloudpull:ItemCount"/>
      </ItemCount>
      <xpathToItem>//*[namespace-uri()='__LIST__WSDL__TYPE__NAMESPACE__' and local-name()='ListResponse']/*[namespace-uri()='http://xmlns.oracle.com/cloud/list/pull' and local-name()='PullResponse']/*[namespace-uri()='http://xmlns.oracle.com/cloud/list/pull' and local-name()='Payload']/*[namespace-uri()='http://xmlns.oracle.com/cloud/list/pull' and local-name()='File']</xpathToItem>
      <xpathToPosition>//*[namespace-uri()='__LIST__WSDL__TYPE__NAMESPACE__' and local-name()='ListResponse']/*[namespace-uri()='http://xmlns.oracle.com/cloud/list/pull' and local-name()='PullResponse']/*[namespace-uri()='http://xmlns.oracle.com/cloud/list/pull' and local-name()='position']</xpathToPosition>
      <xpathToPullContext>//*[namespace-uri()='__LIST__WSDL__TYPE__NAMESPACE__' and local-name()='ListResponse']/*[namespace-uri()='http://xmlns.oracle.com/cloud/list/pull' and local-name()='PullResponse']/*[namespace-uri()='http://xmlns.oracle.com/cloud/list/pull' and local-name()='pullContext']</xpathToPullContext>
      <xsl:copy-of select="$bpelContext"/>
      <Payload>
        <xsl:copy-of select="//ftp:ListResponse"/>
      </Payload>
    </BpelPullResponse>
  </xsl:template>
</xsl:stylesheet>