<?xml version = '1.0' encoding = 'UTF-8'?>
<!--
Copyright (c) 2020, Oracle and/or its affiliates.
Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
-->
<xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:nstrgdfl="http://xmlns.oracle.com/cloud/generic/rest/fault/collocatedics/CallAccountCreation" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://xmlns.oracle.com/cloud/adapter/collocatedics/CallAccountCreation_REQUEST" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/collocatedics/CallAccountCreation_REQUEST/types" xmlns:nsmpr0="http://xml.oracle.com/adapters/extension" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr oraext xsd xp20 ora oracle-xsl-mapper xsi fn nsmpr0 xsl ignore01 ns42 ns43 ns44" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/atpdatabase/GetCreationRequestsFromATP_REQUEST/types" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:tns="http://xmlns.oracle.com/cloud/adapter/atpdatabase/GetCreationRequestsFromATP_REQUEST" xmlns:flt="http://xmlns.oracle.com/cloud/generic/service/fault" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:orajs0="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath1510397549" xmlns:ns21="http://www.oracle.rest.converters.autogeneratedns.com/collocatedics/CallAccountCreation_REQUEST" xmlns:orajs2="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath86288" xmlns:orajs1="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath479716033" xmlns:orajs3="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath565719231" xmlns:ns2="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.resources.icsxpathfunctions.ICSInstanceTrackingFunctions" xmlns:ns0="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadJSONPayload_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/stagefile/WriteStageJSONString_REQUEST/types" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:ns33="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadJSONPayload_REQUEST" xmlns:ns35="http://xmlns.oracle.com/cloud/adapter/stagefile/WriteStageJSONString_REQUEST" xmlns:ns36="http://xmlns.oracle.com/cloud/ics/file/v1/types" xmlns:ns37="http://xmlns.oracle.com/cloud/staging/write" xmlns:encoding="UTF8" xmlns:ns31="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadJSONPayload/types" xmlns:ns38="http://xmlns.oracle.com/pcbpel/adapter/opaque/" xmlns:nsmpr4="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:nsmpr5="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadJSonPayload_REQUEST/types" xmlns:nsmpr6="http://xmlns.oracle.com/cloud/adapter/stagefile/WriteStageJSonString_REQUEST/types" xmlns:ns42="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadJSonPayload/types" xmlns:ns43="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadJSonPayload_REQUEST" xmlns:ns44="http://xmlns.oracle.com/cloud/adapter/stagefile/WriteStageJSonString_REQUEST">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_77">
            <oracle-xsl-mapper:schema location="../../processor_232/resourcegroup_233/ReadJSonPayload_REQUEST.wsdl" xml:id="id_78"/>
            <oracle-xsl-mapper:rootElement name="ReadResponse" namespace="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadJSonPayload_REQUEST/types" xml:id="id_79"/>
            <oracle-xsl-mapper:param name="ReadJSonPayload" xml:id="id_80"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_61/inbound_62/resourcegroup_63/CallAccountCreation_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="default" namespace="http://xmlns.oracle.com/cloud/adapter/collocatedics/CallAccountCreation_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ReadJSonPayload" xml:id="id_99"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:default xml:id="id_12">
         <nstrgmpr:request-wrapper xml:id="id_31">
            <ns21:Account xml:id="id_32">
               <ns21:id xml:id="id_33">
                  <xsl:value-of xml:id="id_64" select="$ReadJSonPayload/nsmpr5:ReadResponse/ns42:request-wrapper/ns42:Account/ns42:id"/>
               </ns21:id>
            <ns21:name xml:id="id_65">
                  <xsl:value-of xml:id="id_66" select="$ReadJSonPayload/nsmpr5:ReadResponse/ns42:request-wrapper/ns42:Account/ns42:name"/>
               </ns21:name>
               <ns21:branch xml:id="id_67">
                  <xsl:value-of xml:id="id_68" select="$ReadJSonPayload/nsmpr5:ReadResponse/ns42:request-wrapper/ns42:Account/ns42:branch"/>
               </ns21:branch>
            </ns21:Account>
         </nstrgmpr:request-wrapper>
      </nstrgmpr:default>
   </xsl:template>
</xsl:stylesheet>
